//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SK_dogovor()
        {
            this.SK_vid_dogovora = new HashSet<SK_vid_dogovora>();
        }
    
        public int kod_dogovora { get; set; }
        public string data_zakluchenya_dogovora { get; set; }
        public string srok_deystvia { get; set; }
        public string strahovaya_summa { get; set; }
        public string vid_srahovania { get; set; }
        public string tarifnaya_stavka { get; set; }
        public Nullable<int> kod_klienta { get; set; }
        public Nullable<int> kod_kompanii { get; set; }
        public Nullable<int> kod_filiala_kompanii { get; set; }
    
        public virtual SK_filial_kompanii SK_filial_kompanii { get; set; }
        public virtual SK_Klient SK_Klient { get; set; }
        public virtual SK_strahovaya_kompania SK_strahovaya_kompania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_vid_dogovora> SK_vid_dogovora { get; set; }
    }
}
