//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_filial_kompanii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SK_filial_kompanii()
        {
            this.SK_dogovor = new HashSet<SK_dogovor>();
        }
    
        public int kod_filiala_kompanii { get; set; }
        public string nazvanie { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<int> kod_klienta { get; set; }
        public Nullable<int> kod_kompanii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_dogovor> SK_dogovor { get; set; }
        public virtual SK_Klient SK_Klient { get; set; }
        public virtual SK_strahovaya_kompania SK_strahovaya_kompania { get; set; }
    }
}
