//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_Klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SK_Klient()
        {
            this.SK_dogovor = new HashSet<SK_dogovor>();
            this.SK_filial_kompanii = new HashSet<SK_filial_kompanii>();
        }
    
        public int kod_klienta { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public string nomer_telephona { get; set; }
        public Nullable<int> nomer_dogovora { get; set; }
        public Nullable<int> kod_kompanii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_dogovor> SK_dogovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_filial_kompanii> SK_filial_kompanii { get; set; }
        public virtual SK_strahovaya_kompania SK_strahovaya_kompania { get; set; }
    }
}
