//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_strahovaya_kompania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SK_strahovaya_kompania()
        {
            this.SK_dogovor = new HashSet<SK_dogovor>();
            this.SK_filial_kompanii = new HashSet<SK_filial_kompanii>();
            this.SK_Klient = new HashSet<SK_Klient>();
        }
    
        public int kod_kompanii { get; set; }
        public string nazvane { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string elektronnaya_pochta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_dogovor> SK_dogovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_filial_kompanii> SK_filial_kompanii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SK_Klient> SK_Klient { get; set; }
    }
}
