//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_vid_dogovora
    {
        public int kod_vida_dogovora { get; set; }
        public string vid_dogovora { get; set; }
        public Nullable<int> kod_dogovora { get; set; }
    
        public virtual SK_dogovor SK_dogovor { get; set; }
    }
}
